### PR TITLE
Initial work

### PR DESCRIPTION
**Pull request by metal0**

### CODE REVIEW

**Comment by zayKenyon** [comment]
Can you create a team project for the cloudflare page so it builds on my commits?

**Comment by metal0** [comment]
> Can you create a team project for the cloudflare page so it builds on my commits?

It does build on your commits, it just errored.
I'm not entirely sure how to make it automatically show error logs here

**Comment by metal0** [comment]
```
<html>
<body>
<!--StartFragment-->



15:16:24.872 | [WARNING] Docs markdown link couldn't be resolved: (/docs/guides/operating-systems/Linux/ubuntu/ubuntu-18.md) in /opt/buildhome/repo/docs/credits.md for version current
15:16:24.873 | [WARNING] Docs markdown link couldn't be resolved: (/docs/guides/solutions/bot/docker.md) in /opt/buildhome/repo/docs/credits.md for version current
15:16:24.936 | [WARNING] Docs markdown link couldn't be resolved: (/docs/guides/operating-systems/Linux/ubuntu/ubuntu-18.md) in /opt/buildhome/repo/docs/guides/operating-systems/intro.md for version current
15:16:24.937 | [WARNING] Docs markdown link couldn't be resolved: (docs/guides/operating-systems/intro.md) in /opt/buildhome/repo/docs/guides/solutions/intro.md for version current
15:16:24.937 | [WARNING] Docs markdown link couldn't be resolved: (/docs/guides/solutions/dashboard/intro.md) in /opt/buildhome/repo/docs/guides/solutions/intro.md for version current
15:16:24.937 | [WARNING] Docs markdown link couldn't be resolved: (/docs/guides/solutions/both/intro.md) in /opt/buildhome/repo/docs/guides/solutions/intro.md for version current
15:16:25.153 | [WARNING] Docs markdown link couldn't be resolved: (/docs/guides/operating-systems/intro.md) in /opt/buildhome/repo/docs/guides/solutions/dashboard/cloudflare.md for version current
15:16:25.244 | [WARNING] Docs markdown link couldn't be resolved: (/docs/services/api.md) in /opt/buildhome/repo/docs/guides/solutions/bot/docker.md for version current
15:16:25.244 | [WARNING] Docs markdown link couldn't be resolved: (/docs/services/dashboard.md) in /opt/buildhome/repo/docs/guides/solutions/bot/docker.md for version current
15:16:25.306 | [WARNING] Docs markdown link couldn't be resolved: (/docs/guides/operating-systems/Linux/ubuntu/ubuntu-18.md) in /opt/buildhome/repo/docs/credits.md for version current
15:16:25.306 | [WARNING] Docs markdown link couldn't be resolved: (/docs/guides/solutions/bot/docker.md) in /opt/buildhome/repo/docs/credits.md for version current
15:16:25.744 | [WARNING] Docs markdown link couldn't be resolved: (/docs/guides/operating-systems/Linux/ubuntu/ubuntu-18.md) in /opt/buildhome/repo/docs/guides/operating-systems/intro.md for version current
15:16:25.754 | [WARNING] Docs markdown link couldn't be resolved: (docs/guides/operating-systems/intro.md) in /opt/buildhome/repo/docs/guides/solutions/intro.md for version current
15:16:25.754 | [WARNING] Docs markdown link couldn't be resolved: (/docs/guides/solutions/dashboard/intro.md) in /opt/buildhome/repo/docs/guides/solutions/intro.md for version current
15:16:25.754 | [WARNING] Docs markdown link couldn't be resolved: (/docs/guides/solutions/both/intro.md) in /opt/buildhome/repo/docs/guides/solutions/intro.md for version current
15:16:25.756 | [WARNING] Docs markdown link couldn't be resolved: (/docs/guides/operating-systems/intro.md) in /opt/buildhome/repo/docs/guides/solutions/dashboard/cloudflare.md for version current
15:16:26.508 | [WARNING] Docs markdown link couldn't be resolved: (/docs/services/api.md) in /opt/buildhome/repo/docs/guides/solutions/bot/docker.md for version current
15:16:26.508 | [WARNING] Docs markdown link couldn't be resolved: (/docs/services/dashboard.md) in /opt/buildhome/repo/docs/guides/solutions/bot/docker.md for version current
15:16:36.549 | ✔ Client: Compiled successfully in 17.31s
15:16:39.015 | ✔ Server: Compiled successfully in 19.74s
15:16:49.462 | [ERROR] Unable to build website for locale en.
15:16:49.463 | [ERROR] Error: Docusaurus found broken links!
15:16:49.463 |  
15:16:49.463 | Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
15:16:49.463 | Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
15:16:49.463 |  
15:16:49.463 | Exhaustive list of all broken links found:
15:16:49.463 |  
15:16:49.463 | - On source page path = /credits:
15:16:49.463 | -> linking to /docs/guides/operating-systems/Linux/ubuntu/ubuntu-18.md
15:16:49.463 | -> linking to /docs/guides/solutions/bot/docker.md
15:16:49.463 |  
15:16:49.463 | - On source page path = /guides/operating-systems/intro:
15:16:49.464 | -> linking to /docs/guides/operating-systems/Linux/ubuntu/ubuntu-18.md
15:16:49.464 |  
15:16:49.464 | - On source page path = /guides/operating-systems/Linux/ubuntu/ubuntu-18:
15:16:49.464 | -> linking to ../../Discord/bot-creation/intro (resolved as: /guides/operating-systems/Discord/bot-creation/intro)
15:16:49.464 |  
15:16:49.464 | - On source page path = /guides/solutions/bot/docker:
15:16:49.464 | -> linking to /docs/services/api.md
15:16:49.464 | -> linking to /docs/services/dashboard.md
15:16:49.464 |  
15:16:49.464 | - On source page path = /guides/solutions/dashboard/cloudflare:
15:16:49.464 | -> linking to /docs/guides/operating-systems/intro.md
15:16:49.464 |  
15:16:49.464 | - On source page path = /guides/solutions/intro:
15:16:49.464 | -> linking to docs/guides/operating-systems/intro.md (resolved as: /guides/solutions/docs/guides/operating-systems/intro.md)
15:16:49.464 | -> linking to /docs/guides/solutions/dashboard/intro.md
15:16:49.464 | -> linking to /docs/guides/solutions/both/intro.md
15:16:49.464

<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```

**Comment by zayKenyon** [comment]
Ah expected this to happen, will implement the relative links plugin pinned in #docs.

**Pull request merged**
